[package]
name = "darkestdev/darknet"
version = "0.1.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
BridgeNet2 = "remnantsofsiren/bridgenet2@1.0.1"
